---

# This is a comment

- name: Install System Packages
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  sudo: yes
  with_items: "{{ system_packages }}"

- name: Clone Django Repository
  git: repo=https://github.com/FoodLust/FL.git
    dest={{ django_home }}
    force=yes depth=1
    verision = {{ repo_version }}

- name: Install Python Dependencies
  pip:
    virtualenv: "{{ venv_home }}"
    state: present
    requirements: "{{ django_home }}/requirements.pip"

- name: Get DB Hostvars
  set_fact:
    db_host: "{{ hostvars[groups[rds_db_instance][0]] }}"

- name: Set DB URL
  set_fact:
    db_url: "{{ db_host.ec2_engine }}://{{ db_host.ec2_master_username }}:{{ DBPASS }}@{{ db_host.ec2__address }}:{{ db_host.ec2__port }}/{{ db_host.ec2_DBName }}"

- name: Run Migrations
  environment:
    FL_SECURITY_KEY: "{{ FL_SECURITY_KEY }}"
    DBURL: "{{ db_host.ec2__address }}"
    DBUSER: "{{ DBUSER }}"
    DBPORT: "{{ DBPORT }}"
    DBPASS: "{{ DBPASS }}"
    DBNAME: "{{ DBNAME }}"
    EMAIL_USER: "{{ EMAIL_USER }}"
    EMAIL_DEFAULT: "{{ EMAIL_DEFAULT }}"
    EMAIL_PW: "{{ EMAIL_PW }}"
    DEBUG: False
  django_manage:
    virtualenv: "{{ venv_home }}"
    app_path: "{{ django_home }}"
    settings: "{{ django_settings }}"
    command: migrate

# - name: Collect Static Files
#   environment:
#     FL_SECURITY_KEY: "{{ FL_SECURITY_KEY }}"
#     DBURL: "{{ db_host.ec2__address }}"
#     DBUSER: "{{ DBUSER }}"
#     DBPORT: "{{ DBPORT }}"
#     DBPASS: "{{ DBPASS }}"
#     DBNAME: "{{ DBNAME }}"
#     EMAIL_USER: "{{ EMAIL_USER }}"
#     EMAIL_DEFAULT: "{{ EMAIL_DEFAULT }}"
#     EMAIL_PW: "{{ EMAIL_PW }}"
#     DEBUG: False
#   django_manage:
#     virtualenv: "{{ venv_home }}"
#     app_path: "{{ django_home }}"
#     settings: foodlust.settings
#     command: collectstatic
